import { React, Fragment } from 'react'

import Image from "next/image"
import HelpIcon from '@material-ui/icons/Help';
import ChatIcon from '@material-ui/icons/Chat';

function question() {
    return (
        <Fragment>
            <div className="faq_area">
                <div className="container">
                    <div className="row">
                        <div className="col-xl-12">
                            <div className="accordion_heading">
                                <h3>Frequently Ask Question</h3>
                            </div>
                            <div id="accordion">
                                <div className="card">
                                    <div className="card-header" id="headingTwo">
                                        <h5 className="mb-0">
                                            <button
                                                className="btn btn-link collapsed"
                                                data-toggle="collapse"
                                                data-target="#collapseTwo"
                                                aria-expanded="false"
                                                aria-controls="collapseTwo"
                                            >
                                                <HelpIcon className="p-2" style={{ fontSize: "4rem" }} />Do The WordPress Hosting Plans Include Email Hosting As Well?
                    </button>
                                        </h5>
                                    </div>
                                    <div
                                        id="collapseTwo"
                                        className="collapse"
                                        aria-labelledby="headingTwo"
                                        data-parent="#accordion"
                                    >
                                        <div className="card-body">

                                            <h2>
                                                Yes, you get Email Hosting on all our WordPress Hosting plans through the WordPress Hosting admin panel- Webmail. For more advanced email solutions, you can either purchase G Suite or our Business Email solution.</h2>
                                        </div>
                                    </div>
                                </div>

                                <div className="card">
                                    <div className="card-header" id="headingOne">
                                        <h5 className="mb-0">
                                            <button
                                                className="btn btn-link collapsed"
                                                data-toggle="collapse"
                                                data-target="#collapseOne"
                                                aria-expanded="false"
                                                aria-controls="collapseOne"
                                            >
                                                <HelpIcon className="p-2" style={{ fontSize: "4rem" }} />Is The Use Of An Existing SSL Certificate With My Website Possible?
                    </button>
                                        </h5>
                                    </div>
                                    <div
                                        id="collapseOne"
                                        className="collapse"
                                        aria-labelledby="headingOne"
                                        data-parent="#accordion"
                                    >
                                        <div className="card-body">

                                            <h2>
                                                An existing SSL certificate cannot be used. A CSR is required to be generated by the WordPress Hosting panel, after which a certificate will be issued that can be installed from the panel.</h2>
                                        </div>
                                    </div>
                                </div>

                                <div className="card">
                                    <div className="card-header" id="headingThree">
                                        <h5 className="mb-0">
                                            <button
                                                className="btn btn-link collapsed"
                                                data-toggle="collapse"
                                                data-target="#collapseThree"
                                                aria-expanded="false"
                                                aria-controls="collapseThree"
                                            >

                                                <HelpIcon className="p-2" style={{ fontSize: "4rem" }} />Are SSL Certificates Included With The WordPress Plans?
                    </button>
                                        </h5>
                                    </div>
                                    <div
                                        id="collapseThree"
                                        className="collapse"
                                        aria-labelledby="headingThree"
                                        data-parent="#accordion"
                                    >
                                        <div className="card-body">
                                            <h2>
                                                A SSL certificate is not currently included with the WordPress Hosting plans. The certificate will have to be purchased by you separately. You can buy a SSL Certificate here.</h2>
                                        </div>
                                    </div>
                                </div>






                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div className="lets_launch launch_bg_1 overlay2">
                <div className="launch_text text-center">
                    <h3>Let’s Launch your Website Now</h3>
                    <p>
                        Our set he for firmament morning sixth subdue darkness creeping
          gathered divide our let god moving. <br />
          Moving in fourth air night bring upon you’re it beast.
        </p>
                    <div className="chat">
                        <a className="boxed_btn_green" href="#" style={{ textDecoration: "none" }}>
                            <ChatIcon />
                            <span>Live Chat</span>
                        </a>
                        <a className="boxed_btn_green2" href="#" style={{ textDecoration: "none" }}>
                            <span>get start now</span>
                        </a>
                    </div>
                </div>
            </div>


        </Fragment>

    )
}

export default question
